DROP TABLE T_PM_CANDIDATO;
DROP TABLE T_PM_FEEDBACK;
DROP TABLE T_PM_USUARIO;
DROP TABLE T_PM_VAGA;
DROP TABLE T_PM_CARREIRA;

CREATE TABLE T_PM_CARREIRA(
	cd_carreira NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	nm_carreira VARCHAR2(30) NOT NULL,
	CONSTRAINT pk_carreira PRIMARY KEY (cd_carreira)
);

CREATE TABLE T_PM_VAGA(
	cd_vaga NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	cd_carreira NUMBER(6) NOT NULL,
	nm_vaga VARCHAR2(50) NOT NULL,
	CONSTRAINT pk_vaga PRIMARY KEY (cd_vaga),
	CONSTRAINT fk_carreira FOREIGN KEY (cd_carreira)
    REFERENCES T_PM_CARREIRA(cd_carreira)	
);

CREATE TABLE T_PM_USUARIO(
	cd_login NUMBER(4) NOT NULL,
	cd_vaga NUMBER(6) NOT NULL,
	cd_senha NUMBER(4) NOT NULL,
	nm_usuario VARCHAR2(30) NOT NULL,
	ds_categoria VARCHAR2(11) NOT NULL,
	dt_admissao_vag DATE NOT NULL,
	CONSTRAINT pk_login PRIMARY KEY (cd_login),
	CONSTRAINT fk_vaga FOREIGN KEY (cd_vaga)
    REFERENCES T_PM_VAGA(cd_vaga)
);

CREATE TABLE T_PM_FEEDBACK(
	cd_feedback NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	cd_login NUMBER(4) NOT NULL,
	vl_feedback NUMBER NOT NULL,
	ds_feedback VARCHAR2(100) NOT NULL,
	dt_envio DATE NOT NULL,
	cd_login_receptor NUMBER(4) NOT NULL,
	CONSTRAINT pk_feedback PRIMARY KEY (cd_feedback),
	CONSTRAINT fk_login FOREIGN KEY (cd_login)
    REFERENCES T_PM_USUARIO(cd_login)
);

INSERT INTO T_PM_CARREIRA(cd_carreira, nm_carreira, ds_skills_basicas)
VALUES (1, 'AAAAA', 'SKILLLLLLL');

INSERT INTO T_PM_VAGA(cd_vaga, cd_carreira, nm_vaga, ds_skill, ds_soft_skill)
VALUES (10, 1, 'PEDREIRO');

INSERT INTO T_PM_USUARIO(cd_login, cd_vaga, cd_senha, nm_usuario, ds_categoria, dt_admissao_vag)
VALUES (1, 10, 1234, 'cleiton', 'colaborador', TO_DATE('26-03-2008', 'dd-mm-yyyy'));


INSERT INTO T_PM_USUARIO(cd_login, cd_vaga, cd_senha, nm_usuario, ds_categoria, dt_admissao_vag)
VALUES (2, 10, 1234, 'wagner', 'colaborador', TO_DATE('26-03-2008', 'dd-mm-yyyy'));

INSERT INTO T_PM_FEEDBACK(cd_feedback, cd_login, vl_feedback, ds_feedback, dt_envio, cd_login_receptor)
VALUES (1, 1, 4, 'muit bom funcionario', TO_DATE('26-03-2008', 'dd-mm-yyyy'), 2);

SELECT * FROM T_PM_USUARIO;
